### ISSUE TITLE
MRAN refuses to install writexl :(

### ISSUE THREAD

**Issue by ZedLeb** [ropensci/writexl#10]
My fault entirely I know - but I have begun working with MRAN - and now can't use this great package!

`Package which is only available in source form, and may need compilation of C/C++/Fortran: ‘writexl’
  These will not be installed`

Anyone have any suggestions (I am rather stuck with MRAN for work reasons at the moment)

Cheers
zedleb

```
Microsoft R Open 3.4.1
The enhanced R distribution from Microsoft
Microsoft packages Copyright (C) 2017 Microsoft Corporation

Using the Intel MKL for parallel mathematical computing(using 2 cores).

Default CRAN mirror snapshot taken on 2017-09-01.
See: https://mran.microsoft.com/.

```

**Comment by ZedLeb** [comment]
I tried installing devtools and running
`devtools::install_github("ropensci/writexl")`

I saw that Rtools downloaded OK and I can located it on my C: drive.  I didn't notice a failed installation - but I guess it did fail (there are admin permissions here at work - hence the MRAN - I was better off with R portable on my USB stick!)

Will there be a possibility of the writexl package happily installing from MRAN snapshot in the future or should I pursue my IT admin to see about installing RTools properly?

```
Downloading GitHub repo ropensci/writexl@master
from URL https://api.github.com/repos/ropensci/writexl/zipball/master
trying URL 'https://cran.rstudio.com/bin/windows/Rtools/Rtools34.exe'
Content type 'application/x-msdos-program' length 108085090 bytes (103.1 MB)
downloaded 103.1 MB

WARNING: Rtools is required to build R packages, but is not currently installed.

Please download and install Rtools 3.4 from http://cran.r-project.org/bin/windows/Rtools/.
Installation failed: Could not find build tools necessary to build writexl
```

**Comment by pgensler** [comment]
Have you tried downloading the package from source, (from the tarball), and seeing if that might work? This can help: https://stackoverflow.com/questions/4739837/how-do-i-install-an-r-package-from-the-source-tarball-on-windows

**Comment by jeroen** [comment]
Is this still an issue? Maybe MRAN just lags behind a bit?

**Comment by ZedLeb** [comment]
Thanks @pgensler and @jeroen 

@jeroen - you're right!  I tried again this morning and got the following.  The package loaded successfully.  And worked like a dream.
Great stuff :)

```
> install.packages("writexl")
Installing package into ‘C:/Users/lebourgeoisz/Documents/R/win-library/3.4’
(as ‘lib’ is unspecified)
Package which is only available in source form, and may need compilation of C/C++/Fortran: ‘writexl’
Do you want to attempt to install these from sources?
y/n: y
installing the source package ‘writexl’

trying URL 'https://mran.microsoft.com/snapshot/2017-09-01/src/contrib/writexl_0.1.tar.gz'
Content type 'application/octet-stream' length 186621 bytes (182 KB)
downloaded 182 KB

* installing *source* package 'writexl' ...
** package 'writexl' successfully unpacked and MD5 sums checked
```
lots of source code...

```
installing to C:/Users/lebourgeoisz/Documents/R/win-library/3.4/writexl/libs/x64
** R
** inst
** preparing package for lazy loading
** help
*** installing help indices
** building package indices
** testing if installed package can be loaded
* DONE (writexl)
```

**Comment by jeroen** [comment]
It still has an old version though. Version 0.2 was released a few weeks ago. Why is mran so outdated?

**Comment by jeroen** [comment]
Ah I see it you are installing from the Sept 01 snapshot. Why are you using mran?
