### ISSUE TITLE
option to not coerce dates to strings

### ISSUE THREAD

**Issue by jkgrain** [ropensci/writexl#16]
It would be really useful to be able to keep dates as dates that can be read by excel.  xlsx files are not really a great way to store data, but they are a great way to feed data into excel.  keeping dates as excel readable dates would make a lot of sense in a bunch of use cases.

btw for now I am using this as a workaround:

`dplyr::mutate(df, date = as.numeric(date - as.Date(0, origin="1899-12-30", tz='UTC')))`

where df is my dataframe and `date` is my column that contains dates.

**Comment by jkgrain** [comment]
of course my workaround breaks the round trip of reading the xlsx back in to R.  So now my workaround is to do a vlookup in excel that converts the date to a string by wrapping the lookup value in the TEXT() function.  so now my vlookup into the file generated by writexl looks like:

`=VLOOKUP(TEXT(lookup_value,"yyyy-mm-dd")`,lookup_range_in_writexl_sheet,column,FALSE)`

It would still be cleaner if writexl wrote a date in a format that excel recognized as a date.

**Comment by danielsjf** [comment]
Just for further reference, there is a date bug as well in Excel. They had some issues with that in readxl.

**Comment by shrektan** [comment]
Would anyone share me the reason that writexl chooses to coerce the `Date` to `Character`? Thanks.

https://github.com/ropensci/writexl/blob/e8d176c33b6dd710fac725b51b99878dbd20da20/R/write_xlsx.R#L36-L38

**Comment by jeroen** [comment]
Should be fixed now!

**Comment by shrektan** [comment]
Thanks!
