### ISSUE TITLE
Apostrophe caused XML problems in workbook

### ISSUE THREAD

**Issue by scientistanton** [ropensci/writexl#17]
Hello,
Not sure if this is a real issue, or how best to report it. A stray comma in an imported CSV caused problems when exported using `write_xlsx`. When I opened the xlsx file it ran a repair job; here is the log:
![image](https://user-images.githubusercontent.com/8278116/36565634-23d9ef1e-1875-11e8-9166-05c4c43f6aba.png)
The repair scrubbed all other records on the problematic sheets in the workbook.

I simply removed the apostrophe from the imported data, so not a big problem, but I thought I should report it.
Thanks,
Anton

**Comment by jeroen** [comment]
Can you give us an example of a data frame that you imported with a stray comma, so that we can reproduce the problem?

**Comment by scientistanton** [comment]
I've found it really hard to reproduce - so I've trimmed the problematic csv and zipped it up (attached). This produces the error:
`library(tidyverse)`
`library(writexl)`
`df <- read_csv("problem.csv")`
`list <- df%>%
  split(.$SHEET)`
`write_xlsx(list, "problem.xlsx")`

[problem.zip](https://github.com/ropensci/writexl/files/1749815/problem.zip)

I think this is a very niche issue. I'm not sure how this csv was generated.

**Comment by scientistanton** [comment]
I should have mentioned - you don't see the error until you open the resulting xlsx file in Excel.

**Comment by jeroen** [comment]
Yes I see it. The problem actually already appears in `read_csv`. Line 15 gets read incorrectly:

```r
> read_csv("~/Downloads/problem.csv")[15,]
Parsed with column specification:
cols(
  SHEET = col_integer(),
  NAME = col_character()
)
# A tibble: 1 x 2
  SHEET NAME                
  <int> <chr>               
1     1 "Ward\x92s Prolific"
```

The word `Wardís` has not been correctly read from the csv and the string is corrupt. I'm not sure how excel reads this csv file actually.

**Comment by jeroen** [comment]
So the problem is that your csv file is encoded in Windows-1252 but R assumes UTF-8. Try this:

```r
library(tidyverse)
library(writexl)
df <- read_csv("~/Downloads/problem.csv")
df$NAME <- iconv(df$NAME, "Windows-1252", "UTF-8")
write_xlsx(df, "works.xlsx")
```
