### ISSUE TITLE
worksheet name

### ISSUE THREAD

**Issue by igordot** [ropensci/writexl#18]
Is it possible to specify the worksheet name with `write_xlsx`? Currently, it just names the sheet as "Sheet1".

**Comment by jeroen** [comment]
Yes put it into a named list:  `write_xlsx(list(first = iris, second = mtcars))`

**Comment by igordot** [comment]
Oh wow! That was easy! Thanks!

**Comment by StephieLaPugh** [comment]
This named my sheets "first, second, third, fourth, fifth" and ignored what I put after each "=".

**Comment by StephieLaPugh** [comment]
FYI, in case anyone is as dumb as me, substitute the names you want for "first" "second" "third", etc.  I made five tabs labeled "first", "second", "third"... Derp

I wish this was explained in the documentation.
