### ISSUE TITLE
Empty string - remove space

### ISSUE THREAD

**Issue by uwdk** [ropensci/writexl#20]
For character column types that also have NA values, NA values show with a space (" ") in the excel output and aren't empty.  Original error was addressed in libxlsxwriter here: https://github.com/jmcnamara/libxlsxwriter/issues/121

This space can be removed now in this line of code

https://github.com/ropensci/writexl/blob/5ef824740bf79d679047654bc8c7dbacb3a6aa57/src/write_xlsx.c#L157-L158

**Comment by fredguinog** [comment]
+1

**Comment by gulligull** [comment]
+1
this is a problem when working with the output from R in excel sheets

**Comment by jeroen** [comment]
I guess there is no way to distinguish a `NA` from an empty string in xlsx? Can you give some example code of how the behavior is problematic?

**Comment by jeroen** [comment]
I have fixed it in https://github.com/ropensci/writexl/commit/e2819eed1aaa8004a2b9ec04a970618472727dc9. I'm still a bit concerned about this. For example if the final row(s) if your data only contain NA values, they completely disappear on the xlsx. But I guess that's how things work in Excel.
