### ISSUE TITLE
supply name of sheet to be written to

### ISSUE THREAD

**Issue by gulligull** [ropensci/writexl#23]
It wold be helpful to be able to name the sheet an output is written into (instead of having the default name "Sheet1".

Similar to openxlsx::write.xlsx(..., sheetName = "my_sheet_name")

**Comment by rdatasculptor** [comment]
I'm not sure if I understand your problem correctly, but maybe you are helped by a named list. If you put your data frame into a named list (like list(my_sheet_name=mydataframe) and you write.xlsx() thuis list I guess you'll get the desired outcome.

**Comment by jeroen** [comment]
You can indeed use a named list to write:

```r
writexl::write_xlsx(list(mysheet = iris), "myfile.xlsx")
```
