### ISSUE TITLE
Add an append option

### ISSUE THREAD

**Issue by Lornebradia** [ropensci/writexl#29]
Would it be possible (I don't know the original `libxlsxwriter` library) to implement an "append" option to write the files? 

The use case is that in many occasions we need to add rows to an existing file.

**Comment by jeroen** [comment]
Unfortunately not. From the [libxlsxwriter FAQ](http://libxlsxwriter.github.io/faq.html) page:

> Q. Can Libxlsxwriter use an existing Excel file as a template?
> No. Libxlsxwriter is designed only as a file writer. It cannot read or modify an existing Excel file.
