### ISSUE TITLE
Feature: write a list of data frames

### ISSUE THREAD

**Issue by jbkunst** [ropensci/writexl#3]
I really like the `openxlsx` feature when you use a list of data frame as argument:

```r
openxlsx::write.xlsx(list(ir = iris, cars = mtcars), "asdf.xlsx")
```
This code creates a workbook with 2 sheets with the respective names (ir and cars).

Thanks again for all your work!

**Comment by jeroen** [comment]
I have added this to the development version. Can you test this?

```r
devtools::install_github("ropensci/writexl")
```
Syntax is the same as for openxlsx:
```r
writexl::write_xlsx(list(ir = iris, cars = mtcars), "mydata.xlsx")
```

**Comment by jbkunst** [comment]
I tested (on windows machines 😅 ) it and works like it should. Thanks.

**Comment by jeroen** [comment]
OK thanks!

**Comment by jeroen** [comment]
This is on CRAN now.

**Comment by BruceZhaoR** [comment]
Awesome!  BTW, how about merging `readxl` & `writexl` into one package?

**Comment by sillasgonzaga** [comment]
please update the documentation about this resource

**Comment by jameshowison** [comment]
This is wonderful.  Thanks.  It works really well with  deframe from the tidyverse (tibble specifically),  e.g.:

```{r}
library(tidyverse)
data(iris)
iris %>% 
  group_by(Species) %>% 
  nest() %>% 
  deframe() %>% 
  write_xlsx("iris_tab_per_species.xlsx")
```

**Comment by enricoferrero** [comment]
Fantastic, thanks! It's probably worth to add to the `write_xlsx()` help page that `x` can be a data frame or a list of data frames.

**Comment by jeroen** [comment]
Can you send a pr for that?

**Comment by enricoferrero** [comment]
Just checked and it's actually already in there, sorry!
```
\item{x}{data frame or named list of data frames that will be sheets in the xlsx}
```
The version on CRAN has the functionality but the docs are not up-to-date.
