### ISSUE TITLE
No warning/error exporting to a directory that doesn't exist or to a read-only existing file

### ISSUE THREAD

**Issue by KyleHaynes** [ropensci/writexl#35]
Not sure if this is an issue across operating systems, however, with Windows (10), if you use `writexl::write_xlsx` to create a file in a directory that doesn't exist, no warning or error is thrown. Also if you attempt to overwrite a read-only file, no error or warning is thrown.

This deviates from quite a few other packages, such as;   
* Base `write.csv`
* `data.table::fwrite`
* `haven::write_sav`.

Not saying that all package behavior should align, but to me it would be ideal if a warning/ error was thrown.

Thanks for such a useful package!

**Comment by sfirke** [comment]
Came here to post this as well, `writexl::write_xlsx(mtcars, "not a valid filepath")` appears to run successfully.  I'm used to other packages like those mentioned above and so if I'm not sure if my filepath is `outputs/` or `output/` I'll just try one and then if it errors, use the other one.  The behavior of `writexl::write_xlsx` in this regard threw me for a loop.

**Comment by IanPainter** [comment]
Same issue. No error is given on failure to create a file. This is a **critical** error and package does not meet standards for basic functionality. Please remove this package from CRAN.

**Comment by jeroen** [comment]
@IanPainter wow that's very rude. This is free software, try making an effort to include an example or PR with bugfix next time. Too late now, you're permanently banned from commenting in this repo.
