### ISSUE TITLE
failure to write list of data.frames

### ISSUE THREAD

**Issue by wolski** [ropensci/writexl#38]
Can't write the following list of data frames (attached in a zipped rds file) into an excel file and NO idea why.

```
xxxx <- readRDS(unzip("failur.zip",files = "failur.rds"))
names(xxxx)
dim(xxxx[[1]])
writexl::write_xlsx(xxxx, path = "test.xlsx")
```

All I am getting is :
Error: Error in writexl: failed to create workbook

Help would be greatly appreciated.

Have nice day
Witek

PS. I am on Windows. 
```
> packageVersion("readxl")
[1] ‘1.3.1’
```
```
> sessionInfo()
R version 3.6.1 (2019-07-05)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 18362)

Matrix products: default

locale:
[1] LC_COLLATE=English_United Kingdom.1252  LC_CTYPE=English_United Kingdom.1252    LC_MONETARY=English_United Kingdom.1252 LC_NUMERIC=C                           
[5] LC_TIME=English_United Kingdom.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     
```

[failur.zip](https://github.com/ropensci/writexl/files/3501004/failur.zip)

**Comment by KyleHaynes** [comment]
Hi @wolski,

The list names of you data are invalid Excel worksheet names.

```R
 nchar(names(xxxx))
[1] 33 55
```

1. They're too long
2. They also contain invalid Excel worksheet characters

Notes from some of my own research:

> Worksheet names must be <= 31 characters and must not contain the following characters:
		# \ / * ? : [ ]
		# I did some testing and couldn't find any others so the below resource looks correct:
			# https://bettersolutions.com/excel/worksheets/naming.htm

If you're not aware, `writexl` takes the name of the list and attempts to create the worksheet with that name, if it's not named, it just defaults to Excel's standard.

i.e 
```R
writexl::write_xlsx(list(iris = iris), path = "iris.xlsx")
```

**Comment by KyleHaynes** [comment]
@jeroen Would be happy to create a pull request that checks for this and is a bit more verbose.

**Comment by jeroen** [comment]
I just tested with the latest version of libxlsxwriter and it says:

```
> writexl::write_xlsx(xxxx, path = "test.xlsx")
Error: Error in writexl: failed to create workbook
[WARNING]: workbook_add_worksheet(): worksheet name '(control.NO.no + patient.HU.no)/2' has error: Worksheet name exceeds Excel's limit of 31 characters.
```

So I think that should be informative?
