### ISSUE TITLE
Unclear error message with sheet names > 31 characters

### ISSUE THREAD

**Issue by krlmlr** [ropensci/writexl#42]
Is there a way to make the error message clearer?

``` r
sheets <- list(
  a234567890123456789012345678901 = data.frame(a = 1),
  a2345678901234567890123456789012 = data.frame(a = 1)
)

writexl::write_xlsx(sheets, tempfile())
#> Error: Error in writexl: failed to create workbook
writexl::write_xlsx(sheets[1], tempfile())
writexl::write_xlsx(sheets[2], tempfile())
#> Error: Error in writexl: failed to create workbook
```

<sup>Created on 2019-12-09 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by jeroen** [comment]
I think libxlsxwriter emits a warning to stdout saying that the name is too long. But we should add a manual check that workbook names cannot be longer than 31 characters.

**Comment by jeroen** [comment]
@libxlsxwriter is there a way to put a callback on the function that emits the warning, or does it always just get sent to stderr?
