### ISSUE TITLE
Consider improving error message when a named sheet name exceeds the max character length supported by Excel

### ISSUE THREAD

**Issue by segoldma** [ropensci/writexl#50]
When trying to pass a named list of dataframes into `writexl::write_xlsx()`, the error thrown is `Error: Error in writexl: failed to create workbook`.

It would be useful if the error message indicated that the sheet name should be shortened.

``` r
library(dplyr)

my_datasets <- list("my_really_really_verbose_sheet_name" = mtcars,
                    "my_short_sheet_name" = storms)

writexl::write_xlsx(x = my_datasets,
                    path = "foo.xlsx")
#> Error: Error in writexl: failed to create workbook
```

<sup>Created on 2020-10-29 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by jeroen** [comment]
Hmm I thought we did this already? Which version of writexl are you using?

**Comment by segoldma** [comment]
Ah! I'm using `writexl_1.2`

**Comment by jeroen** [comment]
https://cran.r-project.org/web/packages/writexl/NEWS
