### ISSUE TITLE
write_xlsx fails silently if no path argument supplied

### ISSUE THREAD

**Issue by arencambre** [ropensci/writexl#51]
`write_xlsx(yyy)` does nothing, gives no error.

`write_xlsx(yyy, "yyy.xlsx")` works as expected: I end up with a spreadsheet named **yyy.xlsx** with the object **yyy** as its data.

If the **path** argument is required, please throw an error when it is not supplied.

I think it would be better if you made **path** optional and used the object name supplied for the **x** argument as the filename. For example, if I run `write_xlsx(yyy)`, then the result would be a spreadsheet named **yyy.xlsx** with the object **yyy** as its data.

**Comment by jeroen** [comment]
The documentation shows that the default path is a temporary file, which is returned by the function So you can do:

```r
library(writexl)
filename <- write_xlsx(iris)
print(filename)
browseURL(filename)
```
