### ISSUE TITLE
Error in libxlsxwriter: 'String exceeds Excel's limit of 32,767 characters.'

### ISSUE THREAD

**Issue by zifeng9527** [ropensci/writexl#52]
Hi, thanks for your package.

I encontered a error when output a dataframe, the characters of some cells of which exceeds 32676.

The programm stopped. 

Is there any optin to labed the exceeded cells, e.g. with "NA", but not stop the programm?

**Comment by jeroen** [comment]
Can you please include example code?

**Comment by zifeng9527** [comment]
library(writexl)

c0 <- c(strrep("a",1),"b")
c1 <- c(strrep("a",32767),"b")
c2 <- c(strrep("a",32768),"b")

data1 <- c()
data2 <- c()

data1$V1 <- as.data.frame(c0)
data1$V2 <- as.data.frame(c1)

data2$V1 <- as.data.frame(c0)
data2$V2 <- as.data.frame(c2)

data1 <- as.data.frame(data1)
data2 <- as.data.frame(data2)

write_xlsx(list("sheet1"=data1, "sheet2"=data2),
           path = "output.xlsx", col_names = TRUE, format_headers = TRUE)


Error: Error in libxlsxwriter: 'String exceeds Excel's limit of 32,767 characters.'


Here is the example code. thanks.

**Comment by zifeng9527** [comment]
> Can you please include example code?

I used for-loop to analyze  hundreds of dataframes. Most of them output normally, however, a few might encounter the error, and will lead the stop of the program.  If there is a paramater to avoid the termination, it will be helpfull.

**Comment by jeroen** [comment]
writexl is behaving as expected here, it gives you an error when the string cannot be converted. 

It is up to you to prepare the data so that it can be written to excel. You could use `nchar()` on the columns and either truncate or replace the cells that are too big. It would be dangerous if writexl would do this because it leads to data loss.

**Comment by nguyentruonglt** [comment]
@jeroen could you please help to explain more? What do you do with nchar() before using writexl to export data frame into excel file?

**Comment by novotny1akub** [comment]
@nguyentruonglt: below is an example how to sanitize the data before you use `writexl`.

```
library(tidyverse)

# example data
df <- tibble(
  v1 = c(strrep("a", 32768),"b"),
  v2 = c(strrep("a", 32767),"b"),
  v3 = 1:2
)

# setting the threshold for the maximum number of characters to be preserved
n_char_to_truncate_threshold <- 32767

# adjusted data.frame where the character columns are truncated so that they do not exceed the threshold of 32767 characters
df2 <- map_df(df, ~ifelse(is.character(.x) & nchar(.x) > n_char_to_truncate_threshold,  str_sub(.x, 1, n_char_to_truncate_threshold), .x))

# checking the result to make sure it is truncated
# you can also use it beforehand to see which columns are the ones causing problems
map_df(df2, ~ifelse(is.character(.x), nchar(.x), NA) )

```
