### ISSUE TITLE
NAs

### ISSUE THREAD

**Issue by gui-salome** [ropensci/writexl#53]
Is it possible to have an option to keep NA values in the resulting Excel spreadsheet? Currently, Excel displays NAs as empty cells. Not sure if this is a problem with Excel itself (or depends on version), but if it is please close the issue.

**Comment by jeroen** [comment]
This is intended behavior.

Excel does not have NAs, so if you want strings with "NA" to appear in your spreadsheet, the best way would be to replace the NA values with strings in your input data, I think.

**Comment by gui-salome** [comment]
Fair enough! Thanks for the explanation!
