### ISSUE TITLE
Error in libxlsxwriter : 'Worksheet row or column index out of range.'

### ISSUE THREAD

**Issue by Harry-Long** [ropensci/writexl#57]
When I write large .xlsx files (more than 1,048,576 rows), I got an error message saying that 'Worksheet row or column index out of range.' I tested my code on a remote server in CentOS 7.0 system as well as a win10 machine, but both give the same error. The "use_zip64" argument doesn't work either.  I'm writing to ask if this is a problem with the data size and if it can be solved. I believe it might be a problem with the source C package "libxlsxwriter".

**Comment by jmcnamara** [comment]
1,048,576 rows is an Excel limit: https://support.microsoft.com/en-us/office/excel-specifications-and-limits-1672b34d-7043-467e-8e27-269d656771c3

writexl/libxlsxwriter can't support more rows than Excel supports.

**Comment by Harry-Long** [comment]
> 1,048,576 rows is an Excel limit: https://support.microsoft.com/en-us/office/excel-specifications-and-limits-1672b34d-7043-467e-8e27-269d656771c3
> 
> writexl/libxlsxwriter can't support more rows than Excel supports.

@jmcnamara Thank you!
