### ISSUE TITLE
write xlsx without any fonts

### ISSUE THREAD

**Issue by toxintoxin** [ropensci/writexl#74]
Thank you for such a great package, it was so fast.

But I have a problem, I'm Chinese and when I use it to export xlsx, the font is always **Song**, which is annoying because numbers and english letters are hard to read in **Song**. In the `openxlsx::write.xlsx`, I see the font is **Calibri** in the result.

Can I solve this problem from somewhere?

**Comment by jmcnamara** [comment]
The `libxlsxwriter` library used by `writexl` uses Calibri as the default font, the same as Excel. If the font is showing as Song then that may be a Windows or Excel setting that is changing it.

**Comment by toxintoxin** [comment]
> The `libxlsxwriter` library used by `writexl` uses Calibri as the default font, the same as Excel. If the font is showing as Song then that may be a Windows or Excel setting that is changing it.

Thank you. So that's why.

FYI, I found change the language setting of `Excel 2016` works.  `选项`>`语言`>`Office 创作语言和校对`, put the English to the top.

**Comment by jmcnamara** [comment]
@toxintoxin that is good to know. Could you close the issue if it is resolved.
