### ISSUE TITLE
Numerical Fields Written to File Incorrect

### ISSUE THREAD

**Issue by rthrowaway** [ropensci/writexl#9]
I wrote the following data.frame to an Excel file using write_xlsx, and the sum of each of the columns does not match if I sum the columns in R. The sum from the Excel file is correct up to 10 decimal places and after that it does not match, and looks like it is truncated after about 15.

`
d <- data.frame(x = rnorm(10000), y = rnorm(10000), z = rnorm(10000))
`

**Comment by jeroen** [comment]
Perhaps this is expected? An excel file is plain text so perhaps the number is saved as text with limited precision? Does this not happen for the `openxslx`package?

**Comment by rthrowaway** [comment]
It happens with the `xlsx` package, so that means it is to be expected then?

**Comment by jeroen** [comment]
I think so, see also https://en.wikipedia.org/wiki/Numeric_precision_in_Microsoft_Excel

**Comment by jeroen** [comment]
Do you share any details about numeric precision in xlsx @jmcnamara?

**Comment by jmcnamara** [comment]
> The sum from the Excel file is correct up to 10 decimal places and after that it does not match, and looks like it is truncated after about 15.

That is correct. Excel uses IEEE 754 doubles to store all numbers so the precision is 15 digits.
